./scripts_png_gen/run_all_styles.sh api_graph_anonymization_md
./scripts_png_gen/run_all_styles.sh api_graph_axis_bounds_md
./scripts_png_gen/run_all_styles.sh api_graph_axis_scale_md
./scripts_png_gen/run_all_styles.sh api_graph_basics_md
./scripts_png_gen/run_all_styles.sh api_graph_color_palettes_md
./scripts_png_gen/run_all_styles.sh api_graph_examples_md
./scripts_png_gen/run_all_styles.sh api_graph_graph_md
./scripts_png_gen/run_all_styles.sh api_graph_heatmap_md
./scripts_png_gen/run_all_styles.sh api_graph_layout_md
./scripts_png_gen/run_all_styles.sh api_graph_legends_md
./scripts_png_gen/run_all_styles.sh api_graph_line_attributes_md
./scripts_png_gen/run_all_styles.sh api_graph_line_styles_md
./scripts_png_gen/run_all_styles.sh api_graph_multi_y_md
./scripts_png_gen/run_all_styles.sh api_graph_outputs_md
./scripts_png_gen/run_all_styles.sh api_graph_theme_md
./scripts_png_gen/run_all_styles.sh api_graph_tick_md
./scripts_png_gen/run_all_styles.sh api_graph_time_shift_md
./scripts_png_gen/run_all_styles.sh api_graph_time_zone_md
./scripts_png_gen/run_all_styles.sh api_graph_vision_md
./scripts_png_gen/run_all_styles.sh asl_alerting_expressions_md
./scripts_png_gen/run_all_styles.sh asl_des_md
./scripts_png_gen/run_all_styles.sh asl_ref_2over_md
./scripts_png_gen/run_all_styles.sh asl_ref_abs_md
./scripts_png_gen/run_all_styles.sh asl_ref_add_md
./scripts_png_gen/run_all_styles.sh asl_ref_alpha_md
./scripts_png_gen/run_all_styles.sh asl_ref_and_md
./scripts_png_gen/run_all_styles.sh asl_ref_area_md
./scripts_png_gen/run_all_styles.sh asl_ref_as_md
./scripts_png_gen/run_all_styles.sh asl_ref_avg_md
./scripts_png_gen/run_all_styles.sh asl_ref_axis_md
./scripts_png_gen/run_all_styles.sh asl_ref_bottomk_md
./scripts_png_gen/run_all_styles.sh asl_ref_bottomk_others_avg_md
./scripts_png_gen/run_all_styles.sh asl_ref_bottomk_others_max_md
./scripts_png_gen/run_all_styles.sh asl_ref_bottomk_others_min_md
./scripts_png_gen/run_all_styles.sh asl_ref_bottomk_others_sum_md
./scripts_png_gen/run_all_styles.sh asl_ref_by_md
./scripts_png_gen/run_all_styles.sh asl_ref_call_md
./scripts_png_gen/run_all_styles.sh asl_ref_cg_md
./scripts_png_gen/run_all_styles.sh asl_ref_clamp_max_md
./scripts_png_gen/run_all_styles.sh asl_ref_clamp_min_md
./scripts_png_gen/run_all_styles.sh asl_ref_clear_md
./scripts_png_gen/run_all_styles.sh asl_ref_color_md
./scripts_png_gen/run_all_styles.sh asl_ref_const_md
./scripts_png_gen/run_all_styles.sh asl_ref_contains_md
./scripts_png_gen/run_all_styles.sh asl_ref_count_md
./scripts_png_gen/run_all_styles.sh asl_ref_cq_md
./scripts_png_gen/run_all_styles.sh asl_ref_decode_md
./scripts_png_gen/run_all_styles.sh asl_ref_delay_md
./scripts_png_gen/run_all_styles.sh asl_ref_depth_md
./scripts_png_gen/run_all_styles.sh asl_ref_derivative_md
./scripts_png_gen/run_all_styles.sh asl_ref_des_epic_signal_md
./scripts_png_gen/run_all_styles.sh asl_ref_des_epic_viz_md
./scripts_png_gen/run_all_styles.sh asl_ref_des_fast_md
./scripts_png_gen/run_all_styles.sh asl_ref_des_md
./scripts_png_gen/run_all_styles.sh asl_ref_des_simple_md
./scripts_png_gen/run_all_styles.sh asl_ref_des_slow_md
./scripts_png_gen/run_all_styles.sh asl_ref_des_slower_md
./scripts_png_gen/run_all_styles.sh asl_ref_dist_avg_md
./scripts_png_gen/run_all_styles.sh asl_ref_dist_max_md
./scripts_png_gen/run_all_styles.sh asl_ref_dist_stddev_md
./scripts_png_gen/run_all_styles.sh asl_ref_div_md
./scripts_png_gen/run_all_styles.sh asl_ref_drop_md
./scripts_png_gen/run_all_styles.sh asl_ref_dup_md
./scripts_png_gen/run_all_styles.sh asl_ref_each_md
./scripts_png_gen/run_all_styles.sh asl_ref_ends_md
./scripts_png_gen/run_all_styles.sh asl_ref_eq_md
./scripts_png_gen/run_all_styles.sh asl_ref_eureka_avg_md
./scripts_png_gen/run_all_styles.sh asl_ref_fadd_md
./scripts_png_gen/run_all_styles.sh asl_ref_fcall_md
./scripts_png_gen/run_all_styles.sh asl_ref_fdiv_md
./scripts_png_gen/run_all_styles.sh asl_ref_filter_md
./scripts_png_gen/run_all_styles.sh asl_ref_fmul_md
./scripts_png_gen/run_all_styles.sh asl_ref_format_md
./scripts_png_gen/run_all_styles.sh asl_ref_freeze_md
./scripts_png_gen/run_all_styles.sh asl_ref_fsub_md
./scripts_png_gen/run_all_styles.sh asl_ref_ge_md
./scripts_png_gen/run_all_styles.sh asl_ref_get_md
./scripts_png_gen/run_all_styles.sh asl_ref_gt_md
./scripts_png_gen/run_all_styles.sh asl_ref_has_md
./scripts_png_gen/run_all_styles.sh asl_ref_head_md
./scripts_png_gen/run_all_styles.sh asl_ref_heatmap_md
./scripts_png_gen/run_all_styles.sh asl_ref_in_md
./scripts_png_gen/run_all_styles.sh asl_ref_integral_md
./scripts_png_gen/run_all_styles.sh asl_ref_le_md
./scripts_png_gen/run_all_styles.sh asl_ref_legend_md
./scripts_png_gen/run_all_styles.sh asl_ref_limit_md
./scripts_png_gen/run_all_styles.sh asl_ref_line_md
./scripts_png_gen/run_all_styles.sh asl_ref_list_md
./scripts_png_gen/run_all_styles.sh asl_ref_ls_md
./scripts_png_gen/run_all_styles.sh asl_ref_lt_md
./scripts_png_gen/run_all_styles.sh asl_ref_lw_md
./scripts_png_gen/run_all_styles.sh asl_ref_map_md
./scripts_png_gen/run_all_styles.sh asl_ref_max_md
./scripts_png_gen/run_all_styles.sh asl_ref_median_md
./scripts_png_gen/run_all_styles.sh asl_ref_min_md
./scripts_png_gen/run_all_styles.sh asl_ref_mul_md
./scripts_png_gen/run_all_styles.sh asl_ref_named_rewrite_md
./scripts_png_gen/run_all_styles.sh asl_ref_ndrop_md
./scripts_png_gen/run_all_styles.sh asl_ref_neg_md
./scripts_png_gen/run_all_styles.sh asl_ref_nip_md
./scripts_png_gen/run_all_styles.sh asl_ref_nlist_md
./scripts_png_gen/run_all_styles.sh asl_ref_node_avg_md
./scripts_png_gen/run_all_styles.sh asl_ref_not_md
./scripts_png_gen/run_all_styles.sh asl_ref_offset_md
./scripts_png_gen/run_all_styles.sh asl_ref_or_md
./scripts_png_gen/run_all_styles.sh asl_ref_order_md
./scripts_png_gen/run_all_styles.sh asl_ref_over_md
./scripts_png_gen/run_all_styles.sh asl_ref_palette_md
./scripts_png_gen/run_all_styles.sh asl_ref_pct_md
./scripts_png_gen/run_all_styles.sh asl_ref_per_step_md
./scripts_png_gen/run_all_styles.sh asl_ref_percentiles_heatmap_md
./scripts_png_gen/run_all_styles.sh asl_ref_percentiles_md
./scripts_png_gen/run_all_styles.sh asl_ref_pick_md
./scripts_png_gen/run_all_styles.sh asl_ref_pow_md
./scripts_png_gen/run_all_styles.sh asl_ref_random_md
./scripts_png_gen/run_all_styles.sh asl_ref_re_md
./scripts_png_gen/run_all_styles.sh asl_ref_reic_md
./scripts_png_gen/run_all_styles.sh asl_ref_roll_md
./scripts_png_gen/run_all_styles.sh asl_ref_rolling_count_md
./scripts_png_gen/run_all_styles.sh asl_ref_rolling_max_md
./scripts_png_gen/run_all_styles.sh asl_ref_rolling_mean_md
./scripts_png_gen/run_all_styles.sh asl_ref_rolling_min_md
./scripts_png_gen/run_all_styles.sh asl_ref_rolling_sum_md
./scripts_png_gen/run_all_styles.sh asl_ref_rot_md
./scripts_png_gen/run_all_styles.sh asl_ref_s_md
./scripts_png_gen/run_all_styles.sh asl_ref_sample_count_md
./scripts_png_gen/run_all_styles.sh asl_ref_sdes_fast_md
./scripts_png_gen/run_all_styles.sh asl_ref_sdes_md
./scripts_png_gen/run_all_styles.sh asl_ref_sdes_simple_md
./scripts_png_gen/run_all_styles.sh asl_ref_sdes_slow_md
./scripts_png_gen/run_all_styles.sh asl_ref_sdes_slower_md
./scripts_png_gen/run_all_styles.sh asl_ref_set_md
./scripts_png_gen/run_all_styles.sh asl_ref_sort_md
./scripts_png_gen/run_all_styles.sh asl_ref_sqrt_md
./scripts_png_gen/run_all_styles.sh asl_ref_srandom_md
./scripts_png_gen/run_all_styles.sh asl_ref_sset_md
./scripts_png_gen/run_all_styles.sh asl_ref_stack_md
./scripts_png_gen/run_all_styles.sh asl_ref_starts_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_avg_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_avg_mf_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_count_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_last_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_max_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_max_mf_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_min_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_min_mf_md
./scripts_png_gen/run_all_styles.sh asl_ref_stat_total_md
./scripts_png_gen/run_all_styles.sh asl_ref_stddev_md
./scripts_png_gen/run_all_styles.sh asl_ref_sub_md
./scripts_png_gen/run_all_styles.sh asl_ref_sum_md
./scripts_png_gen/run_all_styles.sh asl_ref_swap_md
./scripts_png_gen/run_all_styles.sh asl_ref_time_md
./scripts_png_gen/run_all_styles.sh asl_ref_time_span_md
./scripts_png_gen/run_all_styles.sh asl_ref_topk_md
./scripts_png_gen/run_all_styles.sh asl_ref_topk_others_avg_md
./scripts_png_gen/run_all_styles.sh asl_ref_topk_others_max_md
./scripts_png_gen/run_all_styles.sh asl_ref_topk_others_min_md
./scripts_png_gen/run_all_styles.sh asl_ref_topk_others_sum_md
./scripts_png_gen/run_all_styles.sh asl_ref_trend_md
./scripts_png_gen/run_all_styles.sh asl_ref_tuck_md
./scripts_png_gen/run_all_styles.sh asl_ref_vspan_md
./scripts_png_gen/run_all_styles.sh asl_tutorial_md