default_language_version:
    python: python3

# Exclude vendored third-party code from all hooks
exclude: ^third_party/

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: pretty-format-json
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.12.2'
    hooks:
    -   id: ruff
        files: '^(src_python_gui|tests_python_gui)/'
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        files: '^(src_python_gui|tests_python_gui)/'
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        files: '^(src_python_gui|tests_python_gui)/'
        args: ["-L", "THIRDPARTY,fallin"]
